{
 "title": "Count Metric",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(my_app_http_requests_count{},method)"
    }
   },
   {
    "name": "status_code",
    "label": "status_code",
    "query": {
     "query": "label_values(my_app_http_requests_count{},status_code)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(my_app_http_requests_count{},instance)"
    }
   },
   {
    "name": "user",
    "label": "user",
    "query": {
     "query": "label_values(my_app_http_requests_count{},user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count Metric",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Count metric\n\nOur count metric is called `my_app_http_requests_count`. Within this dashboard, you can find various methods to query different information about the application regarding this metric.\n\nIt is important to see that every label attached to our metric represents a different timeseries! This means that in order to have a broader aspect of the application performance, we need to sum up these individual labels. That being said, we also need to specify the labels precisely in order to have fine-grained analysis regarding individual parameters attached to our metric."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "options": {
    "content": "# RPM\n\nThis panel shows the average number of all requests of all types of `methods` and `status_codes` which have been made to all of the `instances` by all of the `users`.\n"
   }
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum (rate(my_app_http_requests_count[1m]))*60",
     "legendFormat": "RPM of all requests"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(my_app_http_requests_count[1m]))*60"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "options": {
    "content": "# RPM per method\n\nThis panel shows the average number of all requests of all types of `status_codes` per individual `methods` which have been made to all of the `instances` by all of the `users`.\n"
   }
  },
  {
   "title": "RPM per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per method",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "options": {
    "content": "# RPM per status code\n\nThis panel shows the average number of all requests of all types of `methods` per individual `status_codes` which have been made to all of the `instances` by all of the `users`.\n"
   }
  },
  {
   "title": "RPM per status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per status code",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "options": {
    "content": "# RPM per instance\n\nThis panel shows the average number of all requests of all types of `methods` and `status_codes` which have been made by all of the `users` to individual `instances`.\n"
   }
  },
  {
   "title": "RPM per method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "sum by (method) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per instance",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "options": {
    "content": "# RPM per user\n\nThis panel shows the average number of all requests of all types of `methods` and `status_codes` which have been made to all of the `instances` by individual `users`.\n"
   }
  },
  {
   "title": "RPM per user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "sum by (user) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per user",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 50 },
   "options": {
    "content": "# RPM per each dashboard variable\n\nThis panel shows the average number of requests per minute according to dashboard variables:\n- `methods`\n- `status_codes`\n- `instances`\n- `users`\n"
   }
  },
  {
   "title": "RPM per each dashboard variable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "sum by (method, status_code, instance, user) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per each dashboard variable",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, status_code, instance, user) (rate(my_app_http_requests_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}