{
 "title": "Histogram Metric",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(my_app_http_requests_count{},method)"
    }
   },
   {
    "name": "status_code",
    "label": "status_code",
    "query": {
     "query": "label_values(my_app_http_requests_count{},status_code)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(my_app_http_requests_count{},instance)"
    }
   },
   {
    "name": "user",
    "label": "user",
    "query": {
     "query": "label_values(my_app_http_requests_count{},user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Histogram Metric",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Histogram metric\n\nOur count metric is called `my_app_http_requests_latency_seconds`. Within this dashboard, you can find various methods to query different information about the application regarding this metric.\n\nIt is important to see that every label attached to our metric represents a different timeseries! This means that in order to have a broader aspect of the application performance, we need to sum up these individual labels. That being said, we also need to specify the labels precisely in order to have fine-grained analysis regarding individual parameters attached to our metric."
   }
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(my_app_http_requests_count[1m]))*60",
     "legendFormat": "RPM of all requests"
    }
   ]
  },
  {
   "title": "Latency (s)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(my_app_http_requests_latency_seconds_sum[1m]))\n/\nsum (rate(my_app_http_requests_latency_seconds_count[1m]))",
     "legendFormat": "RPM of all requests"
    }
   ]
  },
  {
   "title": "RPM per method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM per user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by (user) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per method (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (method) (rate(my_app_http_requests_latency_seconds_sum{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))\n/\nsum by (method) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per status code (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(my_app_http_requests_latency_seconds_sum{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))\n/\nsum by (status_code) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per instance (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(my_app_http_requests_latency_seconds_sum{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))\n/\nsum by (instance) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per user (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum by (user) (rate(my_app_http_requests_latency_seconds_sum{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))\n/\nsum by (user) (rate(my_app_http_requests_latency_seconds_count{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(my_app_http_requests_latency_seconds_bucket{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m]))*60",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram Quantiles for 99%, 95% 50%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(my_app_http_requests_latency_seconds_bucket{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(my_app_http_requests_latency_seconds_bucket{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(my_app_http_requests_latency_seconds_bucket{method=~\"$method\",status_code=~\"$status_code\",instance=~\"$instance\",user=~\"$user\"}[1m])))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}